### PR TITLE
RG validation

### PR DESCRIPTION
**Pull request by raphaelduartepinheiro**
Issue #33

Should be interesting do a code review, maybe there's a way easier to do this, avoiding variables.

### CODE REVIEW

**Comment by Londerson** [comment]
Tanks for your PR @raphaelduartepinheiro only be careful on expectations because RG have a lot of rules, and if you make tests for all of this cases we would be more confident with the algorithm, and you test only the final result, if is true of false.

https://github.com/raphaelduartepinheiro/Validation/commit/84105b369ace338ef0281369845fa5bbd2aac5af

It was also missing tests for Resize::Validatation::validate and Resize::Validatation::validate!

https://github.com/Resize/Validation/blob/master/spec/validation_spec.rb

Im see the code, and it works, and i will merge with master, and implement what is missing ok. Im waiting  for more specs for Resize::Validation::Rules::IsRg

**Comment by Londerson** [comment]
Another thing is this refactorings, i dont know how you run this specs because have another name (Rg instead RG) and you require email file.

I require is_rg file, when you make the fork doest have this file, keep updated your branch master :)

**Comment by raphaelduartepinheiro** [comment]
Right. I mistakenly put the email requirement in this files. Soon I'll commit the adjust. Thanks.

**Comment by Londerson** [comment]
Get the latest updates on the branch master, it is very different from when your fork was made.

**Comment by raphaelduartepinheiro** [comment]
@Londerson, please, take a look now.

**Comment by raphaelduartepinheiro** [comment]
Btw, this validation cover the standard brazilian identity registry, and then, test if the whole number is valid, looking the verification digit. It's a confident test.

**Comment by Londerson** [comment]
I see you updated and made some adjusts, but have some different things, i advise of a look at this page https://help.github.com/articles/syncing-a-fork/ because when you send another Pull Request git will identify all diff code (outdated data) and amend with your PR.

For the tests if have a lot of rules i think is a good idea have tests for all cases, eg:

ID rules:
. Minimum of 4 numbers
. Maximum of 8 numbers
. Have no blank spaces
. Need only 1 Capital letter

and specs:
it "should have a minimum of 4 numbers"
it "should have a maximum of 8 numbers"
it "should have no blank spaces"
it "should have one capital letter"

Although your test can prove that all the rules are valid, for the devs who wish to understand that rules were used, and is looking at the specs to better understand, would be a little frustrated because there is only a one test that validates all the rules at once. In addition more tests for this case will documenting your code better.

**Comment by raphaelduartepinheiro** [comment]
Where did you saw those diffs? 

About the test cases, I will fullfit it better later.

**Comment by Londerson** [comment]
This files for exemple:

https://github.com/raphaelduartepinheiro/Validation/blob/master/lib/resize/rules/is_rg.rb
https://github.com/Resize/Validation/blob/master/lib/resize/rules/is_rg.rb

or this file recently updated:

https://github.com/raphaelduartepinheiro/Validation/blob/master/lib/resize/validation.rb
https://github.com/Resize/Validation/blob/master/lib/resize/validation.rb

**Pull request merged**
